# Generated by Django 5.2.3 on 2026-06-24 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treks_app', '0002_add_coordinates'),
        ('treks_app', '0008_delete_toptrek_delete_whatsnew_and_more'),
    ]

    operations = [
    ]
