# Generated by Django 6.0.5 on 2026-06-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks_app', '0008_delete_toptrek_delete_whatsnew_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Submission', 'verbose_name_plural': 'Contact Submissions'},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='original_image',
        ),
        migrations.AddField(
            model_name='contact',
            name='trek_category',
            field=models.CharField(blank=True, choices=[('adventure', 'Adventure Treks'), ('weekend', 'Weekend Treks'), ('nature', 'Nature Escapes'), ('beach', 'Beach Treks'), ('camping', 'Camping Treks'), ('spiritual', 'Spiritual Treks')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='original_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user_type',
            field=models.CharField(blank=True, choices=[('trekker', 'Trekker'), ('organizer', 'Trek Organizer'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
