# Generated by Django 5.2.14 on 2026-06-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks_app', '0008_delete_toptrek_delete_whatsnew_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(blank=True, max_length=255)),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        
    ]
