# Generated by Django 5.2.14 on 2026-06-22 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks_app', '0009_searchlog_remove_blog_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchlog',
            name='trek',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='treks_app.treklist',
            ),
        ),
    ]