# Generated by Django 5.2.3 on 2026-06-24 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks_app', '0009_merge_20260624_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='original_image',
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='original_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchlog',
            name='trek',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='treks_app.treklist',
            ),
        ),
    ]