# Generated by Django 5.2.14 on 2026-07-08 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treks_app', '0009_searchlog_remove_blog_image_and_more'),
        ('treks_app', '0010_add_trek_category_to_contact'),
        ('treks_app', '0010_remove_blog_image_remove_blog_original_image_and_more'),
    ]

    operations = [
    ]
