# Generated by Django 5.2.14 on 2026-07-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks_app', '0011_merge_20260708_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='treklist',
            name='is_ai_generated',
            field=models.BooleanField(default=False, help_text='True if this trek was created from an OSM search result and may still need review (photo, price, schedule).'),
        ),
    ]
