# Generated by Django 5.2.14 on 2026-07-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks_app', '0012_treklist_is_ai_generated'),
    ]

    operations = [
        migrations.CreateModel(
            name='OsmDraftTrek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('short_desc', models.TextField(blank=True, null=True)),
                ('activities', models.TextField(blank=True, null=True)),
                ('price_start', models.PositiveIntegerField(blank=True, null=True)),
                ('operating_days', models.CharField(blank=True, max_length=200, null=True)),
                ('duration_days', models.CharField(blank=True, max_length=100, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operators', models.ManyToManyField(blank=True, to='treks_app.operator')),
                ('related_treks', models.ManyToManyField(blank=True, to='treks_app.treklist')),
                ('trek_points', models.ManyToManyField(blank=True, to='treks_app.trekpoint')),
            ],
        ),
    ]
