# Generated by Django 5.2.16 on 2026-07-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks_app', '0013_osmdrafttrek'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
