# Generated by Django 5.2.14 on 2026-07-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks_app', '0014_contentsection_contact_deleted_at_contact_is_deleted'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='contentsection',
            name='sub_heading',
            field=models.CharField(blank=True, help_text='Optional subsection heading', max_length=255, null=True),
        ),
    ]
